# Author: Carlo C. del Mundo <cdel@cs.washington.edu>
#
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "images",
    srcs = glob([
        "**/*.JPEG",
    ]),
)

filegroup(
    name = "json",
    srcs = [
        "json/sample_training_set.json"
    ],
)
