# Author: Carlo C. del Mundo <carlo@xnor.ai>
#
package(default_visibility = ["//visibility:public"])

py_library(
    name = "regression_dataset",
    srcs = ["regression_dataset.py"],
    deps = [
        ":utils",
    ],
    srcs_version = "PY3",
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
    srcs_version = "PY3",
)
