# Author: Carlo C. del Mundo <carlo@xnor.ai>
#
package(default_visibility = ["//visibility:public"])

py_binary(
    name = "transfer_weights",
    srcs = ["transfer_weights.py"],
    main = "transfer_weights.py",
    srcs_version = "PY3",
)
